 <?php
 

 $title = 'Add new device';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('device', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('titre'));
 echo $this->formRow($form->get('theme')); 
 echo $this->formRow($form->get('lien'));
 echo $this->formRow($form->get('journal'));
  echo $this->formRow($form->get('user_id'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();