<?php
use Zend\Session\Container;

$session = new Container('User');

 $title = 'Paper Available';
 $this->headTitle($title);
 
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Theme</th>
     <th>Lien</th>
     <th>Journal</th>
     <th>Add me</th>
     <?php if($session->email == "admin@admin.fr"){ 
          print $session->is_admin; ?>
     <th>Update List</th>
     <?php } ?>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($devices as $device) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($device->titre);?></td>
     <td><?php echo $this->escapeHtml($device->theme);?></td>
     <td><?php echo $this->escapeHtml($device->lien);?></td>
     <td><?php echo $this->escapeHtml($device->journal);?></td>
     <td><a href="<?php echo $this->url('device',
             array('action'=>'selected', 'id' => $device->id));?>">Add me</td>
     <td>
      <?php if($session->email == "admin@admin.fr"){ 
          print $session->is_admin; ?>
          
      <a href="<?php echo $this->url('device',
             array('action'=>'edit', 'id' => $device->id));?>">Edit</a>
     
         <a href="<?php echo $this->url('device',
             array('action'=>'delete', 'id' => $device->id));?>">Delete</a>  </td>
          
      <?php } ?>
     
 </tr>    
       
 
 <?php endforeach; ?>
 
 </table>
     
      <?php if($session->email == "admin@admin.fr"){ 
          print $session->is_admin; ?>
     
        
     
         <a href="<?php echo $this->url('device',
             array('action'=>'add'));?>">Add new device</a>

      <?php }