<?php
use Zend\Session\Container;

$session = new Container('User');

 $title = 'My Paper';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Theme</th>
     <th>Lien</th>
     <th>Journal</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($devices as $device) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($device->titre);?></td>
     <td><?php echo $this->escapeHtml($device->theme);?></td>
     <td><?php echo $this->escapeHtml($device->lien);?></td>
     <td><?php echo $this->escapeHtml($device->journal);?></td>
 </tr>    
       
 
 <?php endforeach; ?>
 
 </table>
     
      <?php if($session->is_admin == '1'){ ?>
         <a href="<?php echo $this->url('device',
             array('action'=>'edit', 'id' => $device->id));?>">Edit</a>
         <a href="<?php echo $this->url('device',
             array('action'=>'delete', 'id' => $device->id));?>">Delete</a>
         <a href="<?php echo $this->url('device',
             array('action'=>'add'));?>">Add new device</a>

        <?php }; ?>