<?php
/**
 * Created by PhpStorm.
 * User: lamur
 * Date: 21/01/2016
 * Time: 17:59
 */

use Zend\Session\Container;

$session = new Container('User');

$title = 'Your paper';
$this->headTitle($title);

?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
    </p>

    <table class="table">
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Lien</th>
            <th>Delete me</th>

            <th>&nbsp;</th>
        </tr>
        <?php foreach ($wishs as $wish) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($wish->id);?></td>
                <td><?php echo $this->escapeHtml($wish->titre);?></td>
                <td><?php echo $this->escapeHtml($wish->lien);?></td>
                <td><a href="<?php echo $this->url('wish',
                        array('action'=>'delete', 'id' => $wish->id));?>">Delete</a></td>

            </tr>


        <?php endforeach; ?>

    </table>

